functionsDirectory = "C:\\Users\\alial\\Downloads\\blau-optoelektronik-complete (2)\\blau-optoelektronik\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "C:\\Users\\alial\\Downloads\\blau-optoelektronik-complete (2)\\blau-optoelektronik\\dist\\public"
publishOrigin = "config"
commandOrigin = "config"
command = "pnpm vite build"
functions = "C:\\Users\\alial\\Downloads\\blau-optoelektronik-complete (2)\\blau-optoelektronik\\netlify\\functions"

[build.environment]
NODE_VERSION = "20"
SUPABASE_URL = "https://xtuwjizliuthdgytloju.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0dXdqaXpsaXV0aGRneXRsb2p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ2MTIwMjAsImV4cCI6MjA4MDE4ODAyMH0.U5iQhb_rDZedHFfAMl2tA85jn_kvAp2G6m35CyS0do4"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[dev]
command = "pnpm vite --host"
publish = "dist/public"
autoLaunch = false

[functions]

[functions."*"]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]